// build.rs — turn trace_signals.txt (the signal SSOT) into Rust items.
//
// src/trace.rs `include!`s the generated file, so the compiler binary and
// the plate decoder agree on slots by construction. This script is also
// the enforcement point of the "no slot double-books" rule: a bad
// line here fails the build with the offending line quoted.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn die(line_no: usize, raw: &str, msg: String) -> ! {
    panic!("trace_signals.txt:{line_no}: {msg}\n  > {raw}")
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Split off the next whitespace-delimited token, returning it and the
/// untrimmed rest — so the meaning field stays verbatim.
fn take_field(line: &str) -> (&str, &str) {
    let line = line.trim_start();
    match line.find(char::is_whitespace) {
        Some(at) => (&line[..at], &line[at..]),
        None => (line, ""),
    }
}

fn main() {
    println!("cargo:rerun-if-changed=trace_signals.txt");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let ssot = fs::read_to_string("trace_signals.txt")
        .expect("trace_signals.txt (the signal SSOT) must sit next to Cargo.toml");

    let mut seen_slots = BTreeSet::new();
    let mut seen_names = BTreeSet::new();
    let mut signals: Vec<(u8, String, String, String)> = Vec::new();

    for (idx, raw) in ssot.lines().enumerate() {
        let line_no = idx + 1;
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (slot_str, rest) = take_field(line);
        let (name, rest) = take_field(rest);
        let (owner, rest) = take_field(rest);
        let meaning = rest.trim();
        if slot_str.is_empty() || name.is_empty() || owner.is_empty() || meaning.is_empty() {
            die(
                line_no,
                raw,
                "expected `<slot> <NAME> <owner> <meaning>`".into(),
            );
        }
        let slot: u8 = match slot_str.parse() {
            Ok(s) => s,
            Err(_) => die(line_no, raw, format!("slot `{slot_str}` is not a u8")),
        };
        if !seen_slots.insert(slot) {
            die(line_no, raw, format!("slot {slot} double-booked"));
        }
        if !seen_names.insert(name) {
            die(line_no, raw, format!("name {name} declared twice"));
        }
        if name.is_empty()
            || !name
                .chars()
                .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
        {
            die(line_no, raw, format!("NAME `{name}` must be A-Z, 0-9, _"));
        }
        if owner.chars().any(char::is_whitespace) {
            die(line_no, raw, "owner must be a single token".into());
        }
        if meaning.is_empty() {
            die(line_no, raw, "meaning must not be empty".into());
        }
        signals.push((
            slot,
            name.to_string(),
            owner.to_string(),
            meaning.to_string(),
        ));
    }
    if signals.is_empty() {
        panic!("trace_signals.txt declares no signals");
    }
    signals.sort_by_key(|s| s.0);

    let mut rust = String::from(
        "// @generated by build.rs from trace_signals.txt — edit the SSOT, not this file.\n\n",
    );
    for (slot, name, owner, meaning) in &signals {
        rust.push_str(&format!(
            "#[doc = \"{} ({})\"]\n",
            escape(meaning),
            escape(owner)
        ));
        rust.push_str("#[allow(dead_code)]\n");
        rust.push_str(&format!("pub const TRACE_{name}: u8 = {slot};\n\n"));
    }

    fs::write(Path::new(&out_dir).join("trace_signals.rs"), rust)
        .expect("write generated trace_signals.rs");
}
